name: Publish to npm and GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js for npm registry
      - name: Set up Node.js for npm
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the package
      - name: Build package
        run: npm run build

      # Publish to npm with version tag
      - name: Publish to npm with version tag
        run: npm publish --access public --tag v${{ github.event.repository.packageJson.version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Publish to npm with latest tag
      - name: Publish to npm with latest tag
        run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Deprecate old version
      - name: Deprecate version 1.0.1
        run: npm deprecate @brgman/shapes@1.0.1 "This version is deprecated, please use a newer version."
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Set up Node.js for GitHub Packages
      - name: Set up Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@brgman'
          cache: 'npm'

      # Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}